trigger:

- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'sampleconnection'
    command: 'login'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: Docker@2
  displayName: push an image
  inputs:
    containerRegistry: 'sampleconnection'
    command: 'push'
    Dockerfile: app/Dockerfile